In [1]:
#This file will be our first tutorial towards making a chatbot

#What is chatbot?
#To simulate a conversation between a user and a computer. Automated Responses given due to ML algorithms and to train the data. 

#Two types of chatbot:
#1: self-learning chatbot: Uses ML and AI to save inputs from users and give out results
#2: rule-based

#Target Audience: Normal People
#Ideas: Motivational Chatbot, Suncare chatbot (linked to weather), Music chatbot according to moods.

In [2]:
#How does it work?
#1. Gets input from the user. (GUI)
#2. Process Input (Pre-processing, Data Mining, NLTK (NL generation))
#3. Return value that generates the highest confidence value from the logical adapters or ML parameters (Deep Learning)
#4. Returns the response for the input (GUI)

#Ideas to design a chatbot:
#

In [3]:
#Making a web-app using flask
#App contains a chatbot
#Training the bot
#Make conversation with the bot

In [4]:
#pre-processing
import numpy as np 
import nltk
import nltk.corpus
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.tokenize import blankline_tokenize
from nltk.util import bigrams, trigrams, ngrams
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
word_lem = WordNetLemmatizer()
from nltk.corpus import stopwords

#deep learning libraries
import tensorflow
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import SGD
from keras.models import load_model

import random
import regex as re

#for loading and writing files
import json 
import pickle

/Users/SOFIAN123/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/SOFIAN123/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/SOFIAN123/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/SOFIAN123/anaconda3/lib/python3.7/site-packages/tensorflow/pyth

In [5]:
#Loading the files
intents_file = open('intents_nutribot.json').read()
intents = json.loads(intents_file)

In [6]:
#we need to use NLTK/Stanford NLP to tokenize, stem the sentences so it's easy to do ML on the words for later

In [7]:
labels = [] #the unique intents
responses = [] # these are patterns corresponding to the responses a user may ask. 
doc_x = [] #tokenized form of responses. Used later for BOW model
doc_y = [] #these are the intent tags that will directly correspond to that particular response. Used later for BOW model

In [8]:
for intent in intents['intents']:
    for pattern in intent['patterns']:
        #tokenize the pattern sentences
        word = nltk.word_tokenize(pattern)
        #append method only add one element in list per iteration. That is 'How are you?' -> ['How','are', 'you', '?'] (one element)
        doc_x.append(word)
        #add the tag sentences in doc_y file
        doc_y.append(intent["tag"])
        
        responses.append(pattern)
        
    if intent['tag'] not in labels:
        labels.append(intent['tag'])

In [10]:
print(doc_x) #The tokenized list of sentences.

[['Hi', 'there'], ['How', 'are', 'you'], ['Is', 'anyone', 'there', '?'], ['Hello'], ['Good', 'day'], ['What', "'s", 'up', '?'], ['wassup'], ['What', 'is', 'your', 'purpose', '?'], ['What', 'is', 'your', 'task', '?'], ['What', 'can', 'you', 'help', 'me', 'with', '?'], ['Hey', 'What', 'is', 'your', 'name', '?'], ['name', 'pls'], ['your', 'name', 'plz'], ['I', "'m", 'well', ',', 'thank', 'you'], ['I', "'m", 'happy'], ['I', "'m", 'okay'], ['Meh'], ['Meh', ',', 'been', 'better', '.'], ['I', "'m", 'grumpy'], ['I', "'m", 'well', ',', 'thank', 'you'], ['Meh'], ['Meh', ',', 'been', 'better', '.'], ['I', "'m", 'grumpy'], ['I', "'m", 'happy'], ['I', "'m", 'okay'], ['Where', 'is', 'the', 'thyroid', 'gland', 'located', '?'], ['What', 'is', 'thyroid', 'gland', '?'], ['thyroid'], ['What', 'is', 'hyperthyroidism', '?'], ['hyperthyroidism'], ['Tell', 'me', 'about', 'hyperthyroid'], ['What', 'are', 'the', 'symptoms', 'of', 'hyperthyroidism', '?'], ['What', 'are', 'symptoms', 'of', 'an', 'overactive', 't

In [11]:
doc_y #set of tags corresponding to each sentence
print(doc_y)

['greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'purpose', 'purpose', 'purpose', 'name', 'name', 'name', 'user_happy', 'user_happy', 'user_happy', 'user_sad', 'user_sad', 'user_sad', 'user_grumpy', 'user_grumpy', 'user_grumpy', 'user_grumpy', 'user_grumpy', 'user_grumpy', 'thyroid_info', 'thyroid_info', 'thyroid_info', 'hyperthyroidism', 'hyperthyroidism', 'hyperthyroidism', 'symptoms_hyperthyroidism', 'symptoms_hyperthyroidism', 'symptoms_hyperthyroidism', 'weight_loss_thyroid', 'weight_loss_thyroid', 'heartbeat_thyroid', 'heartbeat_thyroid', 'nervous system', 'heat_thyroid', 'heat_thyroid', 'goiter', 'goiter', 'shortbreath_thyroid', 'shortbreath_thyroid', 'BMI', 'BMI', 'underweight', 'underweight', 'normal_weight', 'normal_weight', 'overweight', 'overweight', 'overweight', 'hypothyroidism', 'hypothyroidism', 'healthy_eating', 'healthy_eating', 'healthy_eating', 'portion_size', 'portion_size', 'portion_size', 'portion_size', 'testing_thyroid', 'tes

In [12]:
labels = sorted(labels) #Unique set of tags
print(labels)
print(len(labels))

['BMI', 'american_breakfast', 'american_dinner', 'american_lunch', 'diet_tips_obesity', 'error', 'food', 'genetic_obesity', 'goiter', 'goodbye', 'greeting', 'health_tips_thyroid', 'healthy_breakfast', 'healthy_dinner', 'healthy_eating', 'healthy_lunch', 'healthy_smoothies', 'healthy_snacks', 'heartbeat_thyroid', 'heat_thyroid', 'hyperthyroidism', 'hypothyroidism', 'indian_breakfast', 'indian_dinner', 'indian_lunch', 'junk_food', 'mexican_breakfast', 'mexican_dinner', 'mexican_lunch', 'name', 'nervous system', 'normal_weight', 'obesity_health_tips', 'obesity_info', 'overweight', 'overweight_exercise', 'portion_size', 'purpose', 'risk_obesity', 'shortbreath_thyroid', 'symptoms_hyperthyroidism', 'testing_thyroid', 'thanks', 'thyroid_info', 'treatment_obesity', 'turkish_breakfast', 'turkish_dinner', 'turkish_lunch', 'underweight', 'underweight_exercise', 'user_grumpy', 'user_happy', 'user_sad', 'water_intake', 'weight_loss_thyroid']
55


In [13]:
print(responses)

['Hi there', 'How are you', 'Is anyone there?', 'Hello', 'Good day', "What's up?", 'wassup', 'What is your purpose?', 'What is your task?', 'What can you help me with?', 'Hey What is your name?', 'name pls', 'your name plz', "I'm well, thank you", "I'm happy", "I'm okay", 'Meh', 'Meh, been better.', "I'm grumpy", "I'm well, thank you", 'Meh', 'Meh, been better.', "I'm grumpy", "I'm happy", "I'm okay", 'Where is the thyroid gland located?', 'What is thyroid gland?', 'thyroid', 'What is hyperthyroidism?', 'hyperthyroidism', 'Tell me about hyperthyroid', 'What are the symptoms of hyperthyroidism?', 'What are symptoms of an overactive thyroid?', 'Tell me about hyperthyroid symptoms', 'Why does hyperthyroid cause weight loss?', 'Why weight loss?', 'Why does heartbeat increase in thyroid?', 'How does heartbeat and thyroid related?', 'How does nervous system control heart?', 'Why heat intolerance?', 'Why does thyroid provide heat intolerance?', 'What is goiter?', 'Does thyroid have any abnorm

In [14]:
#docs -> the responses that the user might give
#tags -> the appropriate tag for a question or response given by the user
#user inputs a response -> chatbot checks the pattern in the dict -> relates the pattern to the appropriate tag -> using the tag, it gives an appropriate response 

In [15]:
# Vocabulary Building attempt 2
lower_case = []
tokens = []
#contractions_list = []
punctuations = []

#Lower-case the sentences
for i in responses:
    lower_case.append(i.lower())

#Creating a contractions dictionary -> essential for converting abbreviated words into proper words.
contractions_dict = { 
"ain't": "am not / are not / is not / has not / have not",
"aren't": "are not / am not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he had / he would",
"he'd've": "he would have",
"he'll": "he shall / he will",
"he'll've": "he shall have / he will have",
"he's": "he has / he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how has / how is / how does",
"i'd": "i had / i would",
"i'd've": "i would have",
"i'll": "i shall / i will",
"i'll've": "i shall have / i will have",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it had / it would",
"it'd've": "it would have",
"it'll": "it shall / it will",
"it'll've": "it shall have / it will have",
"it's": "it has / it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she had / she would",
"she'd've": "she would have",
"she'll": "she shall / she will",
"she'll've": "she shall have / she will have",
"she's": "she has / she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as / so is",
"that'd": "that would / that had",
"that'd've": "that would have",
"that's": "that has / that is",
"there'd": "there had / there would",
"there'd've": "there would have",
"there's": "there has / there is",
"they'd": "they had / they would",
"they'd've": "they would have",
"they'll": "they shall / they will",
"they'll've": "they shall have / they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we had / we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what shall / what will",
"what'll've": "what shall have / what will have",
"what're": "what are",
"what's": "what has / what is",
"what've": "what have",
"when's": "when has / when is",
"when've": "when have",
"where'd": "where did",
"where's": "where has / where is",
"where've": "where have",
"who'll": "who shall / who will",
"who'll've": "who shall have / who will have",
"who's": "who has / who is",
"who've": "who have",
"why's": "why has / why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you had / you would",
"you'd've": "you would have",
"you'll": "you shall / you will",
"you'll've": "you shall have / you will have",
"you're": "you are",
"you've": "you have",
"plz": "please",
"pls": "please",
"wassup": "what has / what is",
"whaat": "what",
}

# Defining a function to replace contracted words.

# re function specifies a set of strings that matches it.
# We loop through each word in the sentences, match it with contractions dictionary, and if it matches, we replace with
# key-value pair.
contractions = re.compile('(%s)' % '|'.join(contractions_dict.keys()))

def expand_contractions(s, contractions_dict=contractions_dict):
     def replace(match):
        return contractions_dict[match.group(0)]
     return contractions.sub(replace, s)
    
contractions_list = [expand_contractions(i) for i in lower_case]

for i in contractions_list:
    word = nltk.word_tokenize(i)
    tokens.extend(word)

punctuation = re.compile(r'[-,?!;()./\|0-9]')
#scan every word in thelist and sub the '?','.'.... with backspace (delete)
for i in tokens:
    j = punctuation.sub("", i)
    
    #if backspace is there, ignore it and only consider the words that have length > 0
    if len(j) > 0:
        punctuations.append(j)    

def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    #get the POS tag for each words and turn into upper case ('PRP,NPN...')
    #[0] -> first row, [1] -> second element, [0] -> first letter
    tag = nltk.pos_tag([word])[0][1][0].upper() 
    #Make a dictionary to map POS -> wordnet dictionary commands
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}

    #get() function is needed to get the key-value pair. by default, it will be wordnet.NOUN if none matches.
    return tag_dict.get(tag, wordnet.NOUN)

lemma = [word_lem.lemmatize(w, get_wordnet_pos(w)) for w in punctuations]

stop_words = set(stopwords.words('english')) 

stop_words_list = [w for w in lemma if not w in stop_words] 

vocab_list = stop_words_list

vocab_list = sorted(list(set(vocab_list)))


print("Making lower case.. ")
print(lower_case)

print("Expanding contraction words.. ")
print(contractions_list)

print("Punctuation removal.. ")
print(punctuations)
print("The number of words are: " + str(len(punctuations)) + "\n")

print("Lemmatizing words: ")
print(lemma)
print("The number of words are: " + str(len(lemma)) + "\n")

print("Removing stop words.. ")
print(stop_words_list)
print("The number of words are: " + str(len(stop_words_list)) + "\n")

print("Final Vocabulary List: ")
print(vocab_list)
print("The number of words are: " + str(len(vocab_list)) + "\n")
print("Vocabulary Building Complete..")

Making lower case.. 
['hi there', 'how are you', 'is anyone there?', 'hello', 'good day', "what's up?", 'wassup', 'what is your purpose?', 'what is your task?', 'what can you help me with?', 'hey what is your name?', 'name pls', 'your name plz', "i'm well, thank you", "i'm happy", "i'm okay", 'meh', 'meh, been better.', "i'm grumpy", "i'm well, thank you", 'meh', 'meh, been better.', "i'm grumpy", "i'm happy", "i'm okay", 'where is the thyroid gland located?', 'what is thyroid gland?', 'thyroid', 'what is hyperthyroidism?', 'hyperthyroidism', 'tell me about hyperthyroid', 'what are the symptoms of hyperthyroidism?', 'what are symptoms of an overactive thyroid?', 'tell me about hyperthyroid symptoms', 'why does hyperthyroid cause weight loss?', 'why weight loss?', 'why does heartbeat increase in thyroid?', 'how does heartbeat and thyroid related?', 'how does nervous system control heart?', 'why heat intolerance?', 'why does thyroid provide heat intolerance?', 'what is goiter?', 'does th

In [16]:
#Now after obtaining the vocabulary, and responses, we need to check whether the intents work or not? 

In [17]:
#We are going to use a K-fold cross validation. We will get a sense of how confused or consistent your intents are?


In [18]:
#need to feed into neural network that will convert the sentences into a numbers 0,1

In [19]:
#bag-of-words approach so that deep learning model will understand

In [20]:
def bag_of_words(response, unique_label, response_label, vocabulary):
    out_empty = [0 for _ in range(len(unique_label))]
    training = []
    output = []
    #x -> the row to consider.
    #doc -> the words within that sentence such as: ['How', 'are', 'you']
    for x, doc in enumerate(response):
        #Bag-of-words
        bag = []

        #Lemmatizing the doc_x file

        Docs = [word_lem.lemmatize(w.lower(), get_wordnet_pos(w)) for w in doc]

        #Now we are trying to match the lemmatized sentences in doc_x to the lemmatizedWords.
        #If it does, add a '1' else add '0'
        for w in vocabulary:
            if w in Docs:
                bag.append(1)
            else:
                bag.append(0)


        output_row = out_empty[:]

        #We are going to look through labels list and see where the tag is and set that value to 1 in output row
        #labels -> unique values of tag
        #doc_y -> just values 
        output_row[unique_label.index(response_label[x])] = 1

        training.append(bag)
        output.append(output_row)
    
    return training, output

training_responses, training_labels = bag_of_words(doc_x, labels, doc_y, vocab_list)

In [21]:
training_responses = np.array(training_responses)
training_labels = np.array(training_labels)

print("Training Response Vector Matrix: " + "\n")
print(training_responses)

print("Training Label Vector Matrix: " + "\n")
print(training_labels)

Training Response Vector Matrix: 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Training Label Vector Matrix: 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
print("Training set Dimensions: " + str(len(training_responses)) + " by " + str(len(training_responses[0])))
print("Testing set Dimensions: " + str(len(training_labels)) + " by " + str(len(training_labels[0])))

#Opening a pickle file and 'wb' to write the files.
#with open("data.pickle", "wb") as f:
#    pickle.dump((words, labels, training, output, doc_x), f)

Training set Dimensions: 143 by 106
Testing set Dimensions: 143 by 55


In [23]:
#Deep learning model starts
#The architecture of our model will be a neural network consisting of 3 Dense layers. 
#The first layer has 128 neurons, second one has 64 and the last layer will have the same neurons as the number of classes/labels.
#output layer will represent different labels that we have placed for data and will give softmax (probablistic) value and the highest value will be produced as result.
#hidden layers do most of the work -> they adjust weights and add biases to make sure the desired result is produced.

In [24]:
# deep neural network model
model = Sequential()
#first layer
model.add(Dense(128, input_shape=(len(training_responses[0]),), activation='relu'))
model.add(Dropout(0.5))
#second layer
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
#third layer - > output with layer size of 14
model.add(Dense(len(training_labels[0]), activation='softmax'))

# Compiling model. SGD with Nesterov accelerated gradient gives good results for this model
#sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()
#Training and saving the model 
hist = model.fit(training_responses, training_labels, epochs=1000, batch_size=32, verbose=1)

print("model is created")

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 128)               13696     
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 55)                3575      
Total params: 25,527
Trainable params: 25,527
Non-trainable params: 0
_________________________________________________________________

Epoch 1/1000
143/143 [==============================] - 0s 2ms/step - loss: 4.0427 - accuracy: 0.0420
Epoch 2/1000


In [25]:
import pickle
#Training is Complete!
with open("data_nutribot.pickle", "wb") as f:
    pickle.dump((vocab_list, labels, training_responses, training_labels), f)

model.save('nutri_bot_model.h5', hist)